spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/dpls_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:plutoski12}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  secret: ${JWT_SECRET:your-local-secret-key-that-is-long-enough-for-hs256-algorithm}
  expiration: 86400000

file:
  upload-dir: uploads

server:
  port: ${PORT:8080}

frontend:
  url: ${FRONTEND_URL:http://localhost:5173}